### ISSUE TITLE
How to set response_type to 'code' on Pop-up Flow ?

### ISSUE THREAD

**Issue by arcl30** [Asana/node-asana#120]
Is there an example on how to configure response_type to "code" using Pop-up Flow?

**Comment by slobak** [comment]
If you are using a popup flow or any in-browser flow, then the grant type you *must* use is the `implicit` grant, for security reasons. The `code` grant type requires sending the app secret to exchange the code for a token. You should never provide your app secret to the client-side code in your app because it would be easily compromised.
