### ISSUE TITLE
Change response_type the toke to code

### ISSUE THREAD

**Issue by giorbismiguel** [Asana/node-asana#144]
How i change when i use : 

client.useOauth({
   flowType: Asana.auth.PopupFlow
});

of toke to code?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694763554707/442144838712062)

**Comment by praecipula** [comment]
Hey there,

Our client library makes the assumption that all browser based auth methods will use the [implicit grant](https://asana.com/developers/documentation/getting-started/auth#implicit-grant) flow, because there's no browser client-side OAuth flow that is more secure. The authorization code grant flow requires there to be a machine somewhere that exchanges the code *and the app's client secret* with Asana's authentication servers, and this exchange of the client secret, if done in the browser, could allow a knowledgeable attacker to determine your app's secret and start impersonating it.

You can see where this gets set [here](https://github.com/Asana/node-asana/blob/8a99170f142127e7ddc2bd9ed1bb98f4a823b27c/lib/auth/base_browser_flow.js#L76) in the base class for all our browser-based authentication methods. While it should be possible to override this with a different implementation of the authorizeUrl function, be sure to know that this will be insecure before attempting it.

This has the unfortunate side effect of requiring users to reauthenticate every hour, which is annoying to be sure, but without storing app secrets somewhere where users can't snoop on the network traffic that's really the best that can be done. OAuth is a bit of a bummer when it comes to this particular use case; there's nothing in the OAuth spec that provides anything better.
