### ISSUE TITLE
client.tasks.findAll() method not returning all tasks.

### ISSUE THREAD

**Issue by pegasussanjay** [Asana/node-asana#146]
client.tasks.findAll() method not returning all tasks (subtasks and sub-subtasks). Am I missing something to pass in argument? I have searched on API and Documentation but no luck! 
Is any other way to get all tasks (tasks, subtasks and sub-subtasks,...)?

**Comment by theaeolianmachine** [comment]
Hi @pegasussanjay, sorry for the delay - we missed some issues showing up in our tracker.

This is intentional, as the `/tasks` endpoint (which is requested via the `client.tasks.findAll()` call) only returns the compact records on the tasks in a provided project or tag (optionally filtered by assignee, workspace, and other fields). You can see the documentation for that endpoint [here](https://asana.com/developers/api-reference/tasks#query) (scroll down a little).

Have you seen the documentation on [Input/Output Options](https://asana.com/developers/documentation/getting-started/input-output-options)? By setting `params.fields` to `this.subtasks` you should be able to get the subtasks as well; similarly, the `expand` option can be useful for gathering this kind of information.

With that being said, take care when recursively grabbing subtasks as this can generate a large server request which can make your application less responsive, and potentially cause the request to fail if it's too large. If you're syncing Asana with another data source, consider using [Webhooks](https://asana.com/developers/api-reference/webhooks) or [Events](https://asana.com/developers/api-reference/events) to selectively pull down information when changes have been made in Asana.

**Comment by theaeolianmachine** [comment]
Hi @pegasussanjay, let us know if you have any more questions - if you feel this isn't resolved, let us know and we'll reopen the issue. Thanks!
