### ISSUE TITLE
webhooks.getAll "Forbidden" Error Has Just Started Appearing

### ISSUE THREAD

**Issue by ewallen88** [Asana/node-asana#156]
Just in the past month or so I've started getting an odd "Forbidden" error soley on the client.webhooks.getAll method. Here's my code:

var client = asana.Client.create().useAccessToken(creds.asanaToken);
client.webhooks.getAll(creds.workspaceId)
        .then(function (response) {
            return response;
})

And here's the error I'm getting:

Unhandled rejection Error: Forbidden
    at Forbidden.AsanaError (GitHub\Asana\Webhook\node_modules\asana\lib\errors\error.js:4:11)
    at new Forbidden (GitHub\Asana\Webhook\node_modules\asana\lib\errors\forbidden.js:5:14)
    at Request._callback (GitHub\Asana\Webhook\node_modules\asana\lib\dispatcher.js:155:23)
    at Request.self.callback (GitHub\Asana\Webhook\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (GitHub\Asana\Webhook\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (GitHub\Asana\Webhook\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

	
As an example, the following bit of code works just fine:
client.projects.findAll(creds.workspaceId)
      .then(function (response) {
          return response;
})

Any ideas?

**Comment by praecipula** [comment]
➤ Joe Trollo commented:

We've seen this before: they've lost access to the resource on the webhook, so the default field expansion hits a 403 when trying to include the resource in each webhook. They can either (1) wait up to eight hours for us to send the heartbeat at which point we see they've lost access and delete the webhook, or (2) use opt_fields to explicitly not include the resource in the response.

**Comment by praecipula** [comment]
➤ Joe Trollo commented:

> then it seems to me like they're possibly confused about how client.projects.findAll will not show the projects they've lost access to

I agree

> what would we send in the heartbeat that indicates that they lost access to the webhook?

We wouldn't send anything. Every time we try to send a webhook, we check a number of things: are the credentials still valid? Is the resource untrashed? Is the resource visible to the user? If any of those are not true, we trash the webhook. Then it would no longer appear in these results, so it wouldn't cause a 403. I mention the heartbeat because, if nothing else happens, we're guaranteed to perform that check within eight hours.

**Comment by praecipula** [comment]
➤ Matt Bramlage commented:

Ah, goooot it. It looks like the webhook will trash itself under these conditions:

  * Handshake failure
  * Repeated delivery failure after some period (7 days)
  * Access control failure when the remote job triggers (https://github.com/Asana/codez/blob/next-master/apps/asana/jobs/webhook_remote_job.js#L83)

and that's pretty much it.

So this should only happen as long as the webhook doesn't try to deliver anything - and it would potentially not deliver events to this particular user so long as the project doesn't change in any way (so there are no webhook events to try to send) for up to 8 hours, when the heartbeat would attempt a delivery. TIL.

**Comment by praecipula** [comment]
➤ Matt Bramlage commented:

[Also, just to note: we got ensnared again by the fact that Unito is syncing these comments - that's one reason we've moved to internal discussions happening in the subtasks on these tasks that get multi-homed into [⏳New Devsla](https://app.asana.com/0/642495334379568/list). I'm deleting the comments by hand in the client library repo, which I think will work, but we might want to move further discussion into the subtask.]

**Comment by praecipula** [comment]
Hey @ewallen88 ,

Yes, it turns out there is a circumstance where this is expected behavior, even if it's a bit unintuitive. If you lose access to the resource, and the resource is unchanged (so there are no webhook events to deliver), during the time that you still have an untrashed webhook and the resource is gone for you you might see this happen. The issue here is that for access control, when the resource goes away we make sure you can't see _anything_, including any IDs of the resources. This could be used to infer that the resource in fact exists, for instance, which leaks information - a security issue.

Whenever webhooks attempt a delivery, they check the access control of the current user (the creator of the webhook) and will self-trash if the user has lost access. The thing is, this check will only happen when the webhook has something to deliver, which means either the project or its tasks have changed somehow (which, if you lose access, must be done by another user) or the webhook schedules a heartbeat event - an empty event we send out after (at most) 8 hours.

During that time, you will be in this ^ state, where trying to get webhooks will fail because one of the resources you have a webhook on refuses to allow you to see it - and the whole request fails. This is different than when you do `client.projects.findAll`, which will simply filter / hide the resources you can't see instead of failing the request.

Our API team is aware of this scenario and has triaged it for future webhook work, so sorry about the confusion here. In any case, this should resolve itself in no more than 8 hours, and considerably sooner if the project changes often, so we hope that in the short term this is something that you can work around until we have something more intuitive implemented on our side. Thanks!

**Comment by ewallen88** [comment]
Thanks @praecipula for the write-up.

**Comment by ewallen88** [comment]
Actually @praecipula I'm seeing some more bizarre behavior with this one that I don't think is exactly what you described above.

I have the following task in a Project: https://app.asana.com/0/600956486758204/584556243857702

I can create a webhook on the task ("584556243857702") with no issue, but when I try to create it on the project ("600956486758204") is gives me the same "Forbidden" error.

Have I overloaded the webhook count on the project? Or is this still the expected behavior within this wait period?

**Comment by praecipula** [comment]
➤ Hussain Jaffery commented:

Just a note, I merged in the webhooks read endpoint migration this morning. Shouldn't affect anything, but worth keeping an eye out, if anyone has any issues with /webhook/ or /webhooks/

**Comment by praecipula** [comment]
It's certainly possible! When you try to create a webhook:

- With the same user
- On the same resource
- With the same target (callback address)

you can get a Forbidden response. In this circumstance, take a look at the response body: it will read

"Duplicated webhook. You already have an existing webhook for the given resource and target. Delete the old one before creating another."

**Comment by ewallen88** [comment]
Thanks @praecipula you were right about that, thanks! I'm back up and running
