### ISSUE TITLE
Get 401 error when using personal access token

### ISSUE THREAD

**Issue by pruales** [Asana/node-asana#166]
I can use my token on postman and get a 200, but I get a 401 when I use this package. I followed the same style as the events example so I'm not sure why this is happening.

**Comment by jjschnei** [comment]
Hi @pruales, my guess is that the issue is being caused by a bug that is overwriting the headers (which includes your token).  We [recently resolved the issue](https://github.com/Asana/node-asana/pull/165), so I recommend that you update to v0.16.1 of the client library.  Hopefully, this will solve it for you.

**Comment by jordanskomer** [comment]
@jjschnei - I'm experiencing this issue as well and by the looks of 0.16.1 that should fix it. However, it doesn't appear that 0.16.1 was pushed to npm yet. Not sure if you are aware of this or not, just letting you know so it's on your radar. Thanks for all the hard work!

**Comment by joetrollo** [comment]
Hi @jordanskomer, sorry for the trouble! It seems Travis [claimed the build was successful](https://travis-ci.org/Asana/node-asana/jobs/421732579) but never deployed to NPM. I've done a manual deploy now and [v0.16.1 is available](https://www.npmjs.com/package/asana/v/0.16.1). Can you try again and confirm that you're able to download the new version and that it fixes the issue?

**Comment by jordanskomer** [comment]
@joetrollo - Works like a charm. Thank you!
