### ISSUE TITLE
BUG: Dublicate values when using collection.stream

### ISSUE THREAD

**Issue by nairihar** [Asana/node-asana#176]
Sometimes `collection.stream().on('data'.....` returns dublicate data.

**Comment by rossgrambo** [comment]
Hey @nairihar , due to how pagination is implemented on our stack, this is unfortunately unavoidable. The system basically remembers the last item location that you paged to (or the stream paged to), and if the items has moved, this stream will find the same object.

Example:
Data: [1,2,3,4,5,6,7,8,9,10]
Stream: [1,2,3]...

Stream requests more data >>
Data: [1,2,**3**,4,5,6,7,8,9,10]
Stream: [1,2,3,4,5,6]...

Data changes >>
Data: [1,2,4,5,**6**,3,7,8,9,10]
Stream: [1,2,3,4,5,6,3,7,8]...

We could try and implement logic on the Stream that does extra checking on ids, but this would not catch all scenarios. It's possible for someone to move item 10 to the start of Data. Item 10 would be missed in the Stream. 

If the duplicate case is an issue for you, you'll need to add some logic to ignore them.

Let me know if you have any questions.

Best,
Ross

**Comment by nairihar** [comment]
Thanks, I have already fixed it. I'm using `Map` to handle duplicates.
