### ISSUE TITLE
Support for the new resource identifier 'gid' of type String, instead of the old 'id' of type Number

### ISSUE THREAD

**Issue by SDP190** [Asana/node-asana#179]
According to the docs gid is the new way to indentify resources in Asana, however the current client implementation has only 'id' properties of type number.

Is it still ok to use the old 'id' field?
When will the JS client be updated to support the new 'gid' field?

**Comment by praecipula** [comment]
You should be able to pass a string in where you previously passed an integer even without a new release, because I believe everywhere we were passed this integer we string format it anyway (because HTTP requests all are string based). For example, see https://github.com/Asana/node-asana/blob/master/lib/resources/gen/tasks.js#L71. You should just be able to put the value of the `gid` field in wherever you used to use `id` and it should work.

However, re: release schedule, we're super close to an update release to add portfolios, portfolio memberships, support for our deprecation framework, and more (in fact it's been merged into master already) so keep your eyes peeled for that!

**Comment by SDP190** [comment]
Thanks, appreciate your quick response
