### ISSUE TITLE
Concurreny Rate Limit Enforced: retryAfterSeconds is NaN

### ISSUE THREAD

**Issue by NielsKersic** [Asana/node-asana#210]
I'm updating all subtasks of a main task concurrently using `client.tasks.updateTask()`. For large tasks, this means I hit the rate limit for 15 concurrent writes. However, in the returned error, the `retryAfterSeconds` property is equal to NaN.

**Comment by rossgrambo** [comment]
I believe this is intentional. This field is intended for the requests per minute rate limits, and will show a value there when applicable.

For concurrent requests, we would have to track each of your requests and estimate the duration of each to find the lowest one. This isn't something that the API has built into it, so you're better off using a queue or a library that will limit your concurrent requests. 

A hotfix is to simply run your script in series instead of parallel, but that'll be a performance hit.

Let me know if this doesn't resolve your issue!
