### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by troyastorino** [Asana/node-asana#78]
Assuming this is probably the wrong place to put this, but here goes: 

We're using library version 0.6.0, and are getting an `ECONNREFUSED`. We haven't been getting this at all before, so I'm assuming that we're getting rate-limited by the Asana servers or something?

**Comment by troyastorino** [comment]
Actually, `ECONNREFUSED` is just what we're getting in development environments. In production we're getting `ETIMEDOUT`.

**Comment by slobak** [comment]
StackOverflow may be a better place to post this question; since it's unclear it's specific to the NodeJS library at all. Regardless of site, it would be helpful if you posted more details of the call you're making, and the output you're getting. It's very difficult for anyone to diagnose a problem based on just the presence of an error message without additional context.

If you upgrade to a new version of `node-asana` does the problem go away? It seems like this error would be related to network connectivity.

Another possibility is there's a known issue with requesting projects in the Personal Workspace, so if you're accessing that it could be the cause the API is timing out on you.

**Comment by troyastorino** [comment]
Ya sorry, knew this wouldn't be the right place, and it was very unlikely to be a problem with the Node lib, but wasn't sure where the right place to post was.

The problem is that some task creation calls aren't going through. It seems account related since we started getting the error without any code changes, and the error also appears locally (and also without any changes to code). Some creation calls seem to go through, and for others we get `ECONNREFUSED` errors locally or `ETIMEOUT` errors on the server. My initial thought was rate-limiting, but there is a rate-limiting response from the server, and it doesn't seem like that's what we're getting.

Unfortunately, updating to the new version of `node-asana` didn't fix the problem either.

We created a basic test script, and the problem seems to be irregular. The script is as follows:
```
var asana = require('asana'),
    apiKey = '<api key>';

var client = asana.Client.create().useBasicAuth(apiKey);

client.tasks.create({
  assignee: <assingeeId>,
  name: 'hello',
  notes: 'world',
  projects: [<projectId>],
  workspace: <workspaceId>
});
```

When we ran this script a few times, it would work sometimes, and failed with `ECONNREFUSED` about 40% of the time. We tried creating a separate account and workspace than what we use in production and in development, and got the same behavior. I don't think it's entirely a network issue, though, since we're getting similar failures for our production server which is not on the same network.

**Comment by troyastorino** [comment]
Turns out it was an issue on the Asana side. According to support, some servers for handling API calls were down for a few hours today. Anyway, sorry for cluttering project issue list. As kudos I generally find the node library very nice and very cleanly written, so, great job! :+1:
