### ISSUE TITLE
Unable to call client.users.findAll() without arguments

### ISSUE THREAD

**Issue by andyg5000** [Asana/node-asana#93]
Whenever I call <code>client.users.findAll()</code> I get an Invalid Request

However, if I call <code>client.users.findAll(true)</code> I'm returned the full user list. 

I assume this is a bug since I don't have to do this for other implementations of findAll().

Thanks in advance!

**Comment by noonhub** [comment]
I am investigating this. Thanks for pointing it out. It is quite odd...

**Comment by noonhub** [comment]
This is actually due to the client paginating all requests by default and /users is not able to be paginated unless you provide a workspace as cross-workspace queries cannot be paginated at this time.

The reason that this succeeds when you pass `true` is actually a small bug that has to do with JS types.

A suggested workaround would be to specify a workspace when making this call

    client.users.findAll({workspace: <workspace_id>}).then(function(users){
        console.log(users);
    });

**Comment by noonhub** [comment]
@andyg5000 I am going to close this issue as it is not really a bug. If you want to do cross-workspace queries for users (not recommended) then you can call the dispatcher directly. The `findAll()` method is not meant to be called with a boolean which causes odd behavior in the client and allows the non-paginated query.

Let me know if you have any more questions.
